version: '3.8'
services:
  fungura-v1-dev-api:
    build: .
    container_name: fungura-v1-dev-api
    restart: always
    env_file:
      - .env
    ports:
      - '8086:8086'
    volumes:
      - /test/fungura/files:/test/fungura/files
      - /backup/fungura/dev:/backup/fungura/dev
    networks:
      - fungura-net

networks:
  fungura-net:
    driver: bridge
