name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_HOST bash -s <<'EOF'
            # Exit on any error
            set -e
            
            # Error handling
            trap 'echo "Error on line $LINENO"' ERR
            
            # Source profile and NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            mkdir -p app/Backend-service
            cd app/Backend-service
            
            git checkout main
            git fetch origin main
            git reset --hard origin/main
            
            # Install dependencies
            npm install
            
            # Docker operations
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            
            # Cleanup
            docker system prune -f
          EOF